name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  run-linting:
    # Right way: Just call the file. Do not add "steps:" here.
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: '20'
