name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Call the reusable workflow
  run-linting:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: '22' # Passing the input parameter
